name: Update Hashlists

# Runs every 3 hours
on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  update_hashlist:
    name: Update specified hashlists
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - run: corepack enable pnpm
      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
      - run: pnpm updater
        name: Run updater script
        env:
          COLLECTION_UIDS: ${{ vars.COLLECTION_UIDS }}
          ENDPOINT: ${{ secrets.ENDPOINT }}
          ORDZAAR_BEARER_TOKEN: ${{ secrets.ORDZAAR_BEARER_TOKEN }}
          ORDZAAR_SECRET_KEY: ${{ secrets.ORDZAAR_SECRET_KEY }}
          ORDZAAR_PATH_KEY: ${{ secrets.ORDZAAR_PATH_KEY }}
          ORDZAAR_BOT_TOKEN: ${{ secrets.ORDZAAR_BOT_TOKEN }}
          ORDZAAR_HEADER_KEY: ${{ secrets.ORDZAAR_HEADER_KEY }}
      - name: Prettier
        uses: creyD/prettier_action@31355f8eef017f8aeba2e0bc09d8502b13dbbad1 # v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{json,ts}
          only_changed: True
          github_token: ${{ secrets.ORDZAAR_BOT_TOKEN }}
